const stateDistrictMap = {
  "Andhra Pradesh": {
    code: "AP",
    districts: {
      "Anakapalli": "AKP",
      "Ananthapuram": "ATP",
      "Bapatla": "BPT",
      "Chittoor": "CTR",
      "East Godavari": "EG",
      "Eluru": "ELR",
      "Guntur": "GNT",
      "Kakinada": "KKD",
      "Konaseema": "KSM",
      "Krishna": "KR",
      "Kurnool": "KNL",
      "Nandyal": "NDL",
      "NTR": "NTR",
      "Palnadu": "PLD",
      "Parvathipuram Manyam": "PVP",
      "Prakasam": "PKM",
      "Rajahmundry": "RJY",
      "Srikakulam": "SK",
      "Sri Potti Sriramulu Nellore": "NLR",
      "Sri Sathya Sai": "SSS",
      "Tirupathi": "TPT",
      "Visakhapatnam": "VSP",
      "Vizianagaram": "VZM",
      "West Godavari": "WG",
      "Kadapa": "KDP",
      "Alluri Sitarama Raju": "ASR"
    }
  },
  "Arunachal Pradesh": {
    code: "AR",
    districts: {
      "Anjaw": "ANJ",
      "Changlang": "CHL",
      "Dibang Valley": "DBV",
      "East Kameng": "EKM",
      "East Siang": "ESI",
      "Kamle": "KML",
      "Kra Daadi": "KRD",
      "Kurung Kumey": "KKY",
      "Lepa Rada": "LPR",
      "Lohit": "LOH",
      "Longding": "LON",
      "Lower Dibang Valley": "LDV",
      "Lower Siang": "LSI",
      "Lower Subansiri": "LSB",
      "Namsai": "NAM",
      "Pakke-Kessang": "PKK",
      "Papum Pare": "PPR",
      "Shi Yomi": "SHY",
      "Siang": "SNG",
      "Tawang": "TAW",
      "Tirap": "TRP",
      "Upper Siang": "USI",
      "Upper Subansiri": "USB",
      "West Kameng": "WKM",
      "West Siang": "WSI",
      "Capital Complex (Itanagar)": "CCI",
      "Keyi Panyor": "KYP"
    }
  },
  "Assam": {
    code: "AS",
    districts: {
      "Bajali": "BJL",
      "Baksa": "BKS",
      "Barpeta": "BPT",
      "Biswanath": "BSW",
      "Bongaigaon": "BNG",
      "Cachar": "CAC",
      "Charaideo": "CRD",
      "Chirang": "CHG",
      "Darrang": "DRG",
      "Dhemaji": "DMJ",
      "Dhubri": "DBR",
      "Dibrugarh": "DIB",
      "Dima Hasao": "DMH",
      "Goalpara": "GLP",
      "Golaghat": "GGT",
      "Hailakandi": "HKD",
      "Hojai": "HOJ",
      "Jorhat": "JHT",
      "Kamrup": "KMP",
      "Kamrup Metropolitan": "KMM",
      "Karbi Anglong": "KBA",
      "Karimganj": "KRG",
      "Kokrajhar": "KKJ",
      "Lakhimpur": "LKM",
      "Majuli": "MJU",
      "Morigaon": "MRG",
      "Nagaon": "NGN",
      "Nalbari": "NLB",
      "Sivasagar": "SSG",
      "Sonitpur": "SNT",
      "South Salmara-Mankachar": "SSM",
      "Tamulpur": "TMP",
      "Tinsukia": "TNK",
      "Udalguri": "UDG",
      "West Karbi Anglong": "WKA"
    }
  },
  "Andaman and Nicobar": {
    code: "AN",
    districts: {
      "Nicobar": "NIC",
      "North & Middle Andaman": "NMA",
      "South Andaman": "SDA"
    }
  },

  "Bihar": {
    code: "BR",
    districts: {
      "Araria": "ARR",
      "Arwal": "ARW",
      "Aurangabad": "AUR",
      "Banka": "BKA",
      "Begusarai": "BGS",
      "Bhagalpur": "BGP",
      "Bhojpur": "BHP",
      "Buxar": "BXR",
      "Darbhanga": "DBG",
      "East Champaran": "ECH",
      "Gaya": "GYA",
      "Gopalganj": "GPL",
      "Jamui": "JMU",
      "Jehanabad": "JHD",
      "Kaimur (Bhabua)": "KMR",
      "Kahar": "KTR",
      "Khagaria": "KHG",
      "Kishanganj": "KSG",
      "Lakhisarai": "LKS",
      "Madhepura": "MDP",
      "Madhubani": "MDB",
      "Munger": "MGR",
      "Muzaffarpur": "MZP",
      "Nalanda": "NLD",
      "Nawada": "NWD",
      "Patna": "PTA",
      "Purnia": "PRN",
      "Rohtas": "RTS",
      "Saharsa": "SHS",
      "Samastipur": "SMT",
      "Saran": "SRR",
      "Sheikhpura": "SKP",
      "Sheohar": "SHO",
      "Sitamarhi": "STM",
      "Siwan": "SWN",
      "Supaul": "SPL",
      "Vaishali": "VSH",
      "West Champaran": "WCH"
    }
  },

  "Chhattisgarh": {
    code: "CG",
    districts: {
      "Balod": "BLD",
      "Baloda Bazar": "BBZ",
      "Balrampur-Ramanujganj": "BRG",
      "Bastar": "BST",
      "Bemetara": "BMT",
      "Bijapur": "BJP",
      "Bilaspur": "BLP",
      "Dantewada (Dakshin Bastar)": "DNT",
      "Dhamtari": "DHT",
      "Durg": "DUR",
      "Gariaband": "GRB",
      "Gaurela-Pendra-Marwahi": "GPM",
      "Janjgir-Champa": "JGC",
      "Jashpur": "JSP",
      "Kabirdham (Kawardha)": "KBD",
      "Kanker (Uttar Bastar)": "KKE",
      "Khairagarh-Chhuikhadan-Gandai": "KCG",
      "Kondagaon": "KDN",
      "Korba": "KRB",
      "Koriya (Korea)": "KRY",
      "Mahasamund": "MSM",
      "Manendragarh-Chirmiri-Bharatpur": "MCB",
      "Mohla-Manpur-Ambagarh Chowki": "MMA",
      "Mungeli": "MGL",
      "Narayanpur": "NRP",
      "Raigarh": "RIG",
      "Raipur": "RPR",
      "Rajnandgaon": "RJN",
      "Sarangarh-Bilaigarh": "SRG",
      "Sukma": "SKM",
      "Surajpur": "SJP",
      "Surguja": "SGJ",
      "Sakti": "SKT"
    }
  },
  "Chandigarh": {
    code: "CH",
    districts: {
      "Chandigarh": "CDG"
    }
  },

  "Delhi": {
    code: "DL",
    districts: {
      "Central Delhi": "CDL",
      "East Delhi": "EDL",
      "New Delhi": "NDL",
      "North Delhi": "NOD",
      "North East Delhi": "NED",
      "North West Delhi": "NWL",
      "Shahdara": "SHDA",
      "South Delhi": "SDL",
      "South East Delhi": "SED",
      "South West Delhi": "SWD",
      "West Delhi": "WDL"
    }
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    code: "DNHDD",
    districts: {
      "Dadra & Nagar Haveli": "DNH",
      "Daman": "DMN",
      "Diu": "DIU"
    }
  },


  "Goa": {
    code: "GA",
    districts: {
      "North Goa": "NGA",
      "South Goa": "SGA"
    }
  },
  "Gujarat": {
    code: "GJ",
    districts: {
      "Ahmedabad": "AMD",
      "Amreli": "AML",
      "Anand": "AND",
      "Aravalli": "ARV",
      "Banaskantha": "BNK",
      "Bharuch": "BRC",
      "Bhavnagar": "BHV",
      "Botad": "BTD",
      "Chhota Udaipur": "CDU",
      "Dahod": "DHD",
      "Dang": "DNG",
      "Devbhoomi Dwarka": "DWD",
      "Gandhinagar": "GNR",
      "Gir Somnath": "GSM",
      "Jamnagar": "JMN",
      "Junagadh": "JND",
      "Kutch": "KCH",
      "Kheda": "KHD",
      "Mahisagar": "MHS",
      "Mehsana": "MHSN",
      "Morbi": "MRB",
      "Narmada": "NRD",
      "Navsari": "NVS",
      "Panchmahal": "PCH",
      "Patan": "PTN",
      "Porbandar": "PBD",
      "Rajkot": "RJK",
      "Sabarkantha": "SBK",
      "Surat": "SUR",
      "Surendranagar": "SRN",
      "Tapi": "TPI",
      "Vadodara": "VDR",
      "Valsad": "VLS"
    }
  },

  "Haryana": {
    code: "HR",
    districts: {
      "Ambala": "AMB",
      "Bhiwani": "BHW",
      "Charkhi Dadri": "CKD",
      "Faridabad": "FRD",
      "Fatehabad": "FTB",
      "Gurugram": "GRG",
      "Hisar": "HSR",
      "Jhajjar": "JJR",
      "Jind": "JID",
      "Kaithal": "KTL",
      "Karnal": "KNL",
      "Kurukshetra": "KKR",
      "Mahendragarh": "MHR",
      "Nuh": "NUH",
      "Palwal": "PLW",
      "Panchkula": "PKL",
      "Panipat": "PNP",
      "Rewari": "RWR",
      "Rohtak": "RTK",
      "Sirsa": "SRS",
      "Sonipat": "SNP",
      "Yamunanagar": "YMN"
    }
  },
  "Himachal Pradesh": {
    code: "HP",
    districts: {
      "Bilaspur": "BLP",
      "Chamba": "CHA",
      "Hamirpur": "HMP",
      "Kangra": "KGR",
      "Kinnaur": "KNR",
      "Kullu": "KUL",
      "Lahaul and Spiti": "LSP",
      "Mandi": "MND",
      "Shimla": "SHM",
      "Sirmaur": "SMR",
      "Solan": "SOL",
      "Una": "UNA"
    }
  },

  "Jharkhand": {
    code: "JH",
    districts: {
      "Bokaro": "BKR",
      "Chatra": "CHT",
      "Deoghar": "DGR",
      "Dhanbad": "DNB",
      "Dumka": "DMK",
      "East Singhbhum": "ESB",
      "Garhwa": "GRW",
      "Giridih": "GRD",
      "Godda": "GDD",
      "Gumla": "GML",
      "Hazaribagh": "HZB",
      "Jamtara": "JMT",
      "Khunti": "KHT",
      "Koderma": "KDR",
      "Latehar": "LTH",
      "Lohardaga": "LRD",
      "Pakur": "PKR",
      "Palamu": "PLM",
      "Ramgarh": "RMG",
      "Ranchi": "RNC",
      "Sahibganj": "SBJ",
      "Seraikela-Kharsawan": "SKK",
      "Simdega": "SDG",
      "West Singhbhum": "WSB"
    }
  },
  "Jammu and Kashmir": {
    code: "JK",
    districts: {
      "Anantnag": "ANTG",
      "Bandipora": "BDP",
      "Baramulla": "BRM",
      "Budgam": "BDG",
      "Doda": "DOD",
      "Ganderbal": "GBL",
      "Jammu": "JAM",
      "Kathua": "KTH",
      "Kishtwar": "KTW",
      "Kulgam": "KLG",
      "Kupwara": "KPW",
      "Poonch": "PNC",
      "Pulwama": "PUL",
      "Rajouri": "RJR",
      "Ramban": "RBN",
      "Reasi": "RES",
      "Samba": "SBA",
      "Shopian": "SPN",
      "Srinagar": "SNR",
      "Udhampur": "UDH"
    }
  },


  "Kerala": {
    code: "KL",
    districts: {
      "Alappuzha": "ALP",
      "Ernakulam": "ERN",
      "Idukki": "IDK",
      "Kannur": "KNR",
      "Kasaragod": "KSD",
      "Kollam": "KLM",
      "Kottayam": "KTM",
      "Kozhikode": "KZD",
      "Malappuram": "MLP",
      "Palakkad": "PKD",
      "Pathanamthitta": "PTT",
      "Thiruvananthapuram": "TVM",
      "Thrissur": "TSR",
      "Wayanad": "WND"
    }
  },
  "Karnataka": {
    code: "KA",
    districts: {
      "Bagalkot": "BGK",
      "Ballari (Bellary)": "BAL",
      "Belagavi (Belgaum)": "BEL",
      "Bengaluru Rural": "BRL",
      "Bengaluru Urban": "BU",
      "Bidar": "BID",
      "Chamarajanagar": "CMG",
      "Chikkaballapur": "CBP",
      "Chikkamagaluru": "CMU",
      "Chitradurga": "CTG",
      "Dakshina Kannada": "DKK",
      "Davanagere": "DVN",
      "Dharwad": "DRW",
      "Gadag": "GDG",
      "Hassan": "HAS",
      "Haveri": "HAV",
      "Kalaburagi (Gulbarga)": "KLG",
      "Kodagu (Coorg)": "KDG",
      "Kolar": "KLR",
      "Koppal": "KOP",
      "Mandya": "MND",
      "Mysuru (Mysore)": "MYR",
      "Raichur": "RCR",
      "Ramanagara": "RMN",
      "Shivamogga (Shimoga)": "SHM",
      "Tumakuru (Tumkur)": "TUM",
      "Udupi": "UDP",
      "Uttara Kannada (Karwar)": "UKA",
      "Vijayapura (Bijapur)": "VJP",
      "Vijayanagara": "VJN",
      "Yadgir": "YDG"
    }
  },

  "Ladakh": {
    code: "LA",
    districts: {
      "Kargil": "KGL",
      "Leh": "LEH"
    }
  },
  "Lakshadweep": {
    code: "LD",
    districts: {
      "Lakshadweep": "LKD"
    }
  },

  "Madhya Pradesh": {
    code: "MP",
    districts: {
      "Agar Malwa": "AGA",
      "Alirajpur": "ALI",
      "Anuppur": "ANU",
      "Ashoknagar": "ASH",
      "Balaghat": "BAL",
      "Barwani": "BAR",
      "Betul": "BET",
      "Bhind": "BHI",
      "Bhopal": "BHO",
      "Burhanpur": "BUR",
      "Chhatarpur": "CTP",
      "Chhindwara": "CHI",
      "Damoh": "DAM",
      "Datia": "DAT",
      "Dewas": "DEW",
      "Dhar": "DHA",
      "Dindori": "DIN",
      "Guna": "GUN",
      "Gwalior": "GWA",
      "Harda": "HAR",
      "Hoshangabad / Narmadapuram": "HOS",
      "Indore": "IND",
      "Jabalpur": "JAB",
      "Jhabua": "JHA",
      "Katni": "KAT",
      "Khandwa": "KHN",
      "Khargone": "KGO",
      "Maihar": "MAI",
      "Mandla": "MNL",
      "Mandsaur": "MDS",
      "Mauganj": "MAU",
      "Morena": "MOR",
      "Narsinghpur": "NAR",
      "Neemuch": "NEE",
      "Niwari": "NIW",
      "Panna": "PAN",
      "Raisen": "RAI",
      "Rajgarh": "RAJ",
      "Ratlam": "RAT",
      "Rewa": "REW",
      "Sagar": "SAG",
      "Satna": "SAT",
      "Sehore": "SEH",
      "Seoni": "SEO",
      "Shahdol": "SHD",
      "Shajapur": "SJR",
      "Sheopur": "SHE",
      "Shivpuri": "SHI",
      "Sidhi": "SID",
      "Singrauli": "SIN",
      "Tikamgarh": "TIK",
      "Ujjain": "UJJ",
      "Umaria": "UMA",
      "Vidisha": "VID"
    }
  },
  "Manipur": {
    code: "MN",
    districts: {
      "Bishnupur": "BSP",
      "Chandel": "CHD",
      "Churachandpur": "CCP",
      "Imphal East": "IME",
      "Imphal West": "IMW",
      "Jiribam": "JBM",
      "Kakching": "KKC",
      "Kamjong": "KMG",
      "Kangpokpi": "KNP",
      "Noney": "NON",
      "Pherzawl": "PHZ",
      "Senapati": "SPT",
      "Tamenglong": "TMG",
      "Tengnoupal": "TNP",
      "Thoubal": "THB",
      "Ukhrul": "UKL"
    }
  },
  "Meghalaya": {
    code: "ML",
    districts: {
      "East Garo Hills": "EGH",
      "East Jaintia Hills": "EJH",
      "East Khasi Hills": "EKH",
      "Eastern West Khasi Hills": "EWK",
      "North Garo Hills": "NGH",
      "Ri Bhoi": "RBI",
      "South Garo Hills": "SGH",
      "South West Garo Hills": "SWG",
      "South West Khasi Hills": "SWK",
      "West Garo Hills": "WGH",
      "West Jaintia Hills": "WJH",
      "West Khasi Hills": "WKH"
    }
  },
  "Mizoram": {
    code: "MZ",
    districts: {
      "Aizawl": "AZL",
      "Champhai": "CMP",
      "Hnahthial": "HNH",
      "Khawzawl": "KZL",
      "Kolasib": "KLB",
      "Lawngtlai": "LWT",
      "Lunglei": "LGL",
      "Mamit": "MMT",
      "Saitual": "STL",
      "Serchhip": "SCP",
      "Siaha": "SIA"
    }
  },

  "Nagaland": {
    code: "NL",
    districts: {
      "Chümoukedima": "CHU",
      "Dimapur": "DMR",
      "Kiphire": "KPR",
      "Kohima": "KHM",
      "Longleng": "LGLN",
      "Mokokchung": "MKC",
      "Mon": "MON",
      "Niuland": "NLDN",
      "Noklak": "NKL",
      "Peren": "PRN",
      "Phek": "PHK",
      "Shamator": "SMTN",
      "Tseminyu": "TSM",
      "Tuensang": "TNS",
      "Wokha": "WKHN",
      "Zunheboto": "ZBT"
    }
  },

  "Odisha": {
    code: "OR",
    districts: {
      "Angul": "ANG",
      "Balangir": "BLGR",
      "Balasore": "BLSR",
      "Bargarh": "BGRH",
      "Bhadrak": "BHDK",
      "Boudh": "BODH",
      "Cuttack": "CTCK",
      "Debagarh (Deogarh)": "DEBG",
      "Dhenkanal": "DHNK",
      "Gajapati": "GJPT",
      "Ganjam": "GJAM",
      "Jagatsinghpur": "JGTP",
      "Jajpur": "JJPR",
      "Jharsuguda": "JSGD",
      "Kalahandi": "KLHN",
      "Kandhamal": "KDML",
      "Kendrapara": "KNDP",
      "Kendujhar (Keonjhar)": "KNJR",
      "Khordha": "KHDA",
      "Koraput": "KRPT",
      "Malkangiri": "MLKG",
      "Mayurbhanj": "MYBN",
      "Nabarangpur": "NBRP",
      "Nayagarh": "NYGH",
      "Nuapada": "NUPD",
      "Puri": "PURI",
      "Rayagada": "RYGD",
      "Sambalpur": "SBLP",
      "Subarnapur (Sonepur)": "SBPR",
      "Sundargarh": "SNDG"
    }
  },

  "Punjab": {
    code: "PB",
    districts: {
      "Amritsar": "AMRS",
      "Barnala": "BRNL",
      "Bathinda": "BTND",
      "Faridkot": "FRDK",
      "Fatehgarh Sahib": "FGHS",
      "Fazilka": "FZLK",
      "Ferozepur": "FRZR",
      "Gurdaspur": "GRDP",
      "Hoshiarpur": "HSRP",
      "Jalandhar": "JLDR",
      "Kapurthala": "KPTL",
      "Ludhiana": "LDHA",
      "Malerkotla": "MLKT",
      "Mansa": "MNSA",
      "Moga": "MOGA",
      "Muktsar": "MKSR",
      "Pathankot": "PTHK",
      "Patiala": "PTLA",
      "Rupnagar": "RPNG",
      "Sahibzada Ajit Singh Nagar (Mohali)": "SASN",
      "Sangrur": "SNGR",
      "Shaheed Bhagat Singh Nagar (Nawanshahr)": "SBSN",
      "Tarn Taran": "TTRN"
    }
  },
  "Puducherry": {
    code: "PY",
    districts: {
      "Karaikal": "KAR",
      "Mahe": "MAH",
      "Puducherry": "PUD",
      "Yanam": "YAN"
    }
  },

  "Rajasthan": {
    code: "RJ",
    districts: {
      "Ajmer": "AJMR",
      "Alwar": "ALWR",
      "Anupgarh": "ANPG",
      "Balotra": "BLTR",
      "Banswara": "BNSW",
      "Baran": "BRAN",
      "Barmer": "BRMR",
      "Beawar": "BAWR",
      "Bharatpur": "BHTP",
      "Bhilwara": "BHLW",
      "Bikaner": "BKNR",
      "Bundi": "BNDI",
      "Chittorgarh": "CTGH",
      "Churu": "CHRU",
      "Dausa": "DAUS",
      "Deeg": "DEEG",
      "Dholpur": "DHLP",
      "Didwana Kuchaman": "DDKM",
      "Dudu": "DUDU",
      "Dungarpur": "DGPR",
      "Ganganagar": "GNGN",
      "Gangapur City": "GPCY",
      "Hanumangarh": "HNMG",
      "Jaipur": "JPR",
      "Jaipur Rural": "JPRR",
      "Jaisalmer": "JSLM",
      "Jalore": "JLRE",
      "Jhalawar": "JHLW",
      "Jhunjhunu": "JJNU",
      "Jodhpur": "JDPR",
      "Jodhpur Rural": "JDPRR",
      "Karauli": "KRLI",
      "Kekri": "KEKR",
      "Khairthal-Tijara": "KHTJ",
      "Kotputli-Behror": "KPBR",
      "Kota": "KOTA",
      "Nagaur": "NGUR",
      "Pali": "PALI",
      "Pratapgarh": "PTPG",
      "Rajsamand": "RJSD",
      "Salumbar": "SLMB",
      "Sanchore": "SNCR",
      "Sawai Madhopur": "SWMP",
      "Shahpura": "SHHP",
      "Sikar": "SIKR",
      "Sirohi": "SRHI",
      "Tonk": "TONK",
      "Udaipur": "UDPR"
    }
  },

  "Sikkim": {
    code: "SK",
    districts: {
      "Gangtok": "GNTK",
      "Gyalshing": "GYS",
      "Mangan": "MGN",
      "Namchi": "NMC",
      "Pakyong": "PKY",
      "Soreng": "SOR"
    }
  },

  "Telangana": {
    code: "TS",
    districts: {
      "Adilabad": "ADB",
      "Bhadradri Kothagudem": "BDK",
      "Hanamkonda": "HNK",
      "Hyderabad": "HYD",
      "Jagital": "JGT",
      "Jangaon": "JNN",
      "Jayshankar Bhupalpally": "JBP",
      "Jogulamba Gadwal": "JGL",
      "Kamareddy": "KMR",
      "Karimnagar": "KRMR",
      "Khammam": "KMM",
      "Kumuram Bheem Asifabad": "KBA",
      "Mahabubabad": "MBD",
      "Mahabubnagar": "MBNR",
      "Mancherial": "MCL",
      "Medak": "MDK",
      "Medchal-Malkagiri": "MLG",
      "Mulugu": "MLGU",
      "Nagarkurnool": "NGL",
      "Nalgonda": "NLG",
      "Narayanpet": "NPT",
      "Nirmal": "NML",
      "Nizamabad": "NZB",
      "Peddapalli": "PDL",
      "Rajanna Sircilla": "RSC",
      "Ranga Reddy": "RRD",
      "Sangareddy": "SGD",
      "Siddipet": "SDP",
      "Suryapet": "SRPT",
      "Vikarabad": "VKB",
      "Wanaparthy": "WNP",
      "Warangal": "WRG",
      "Yadadri Bhuvanagiri": "YBG"
    }
  },
  "Tamil Nadu": {
    code: "TN",
    districts: {
      "Ariyalur": "ARI",
      "Chengalpattu": "CHP",
      "Chennai": "CHN",
      "Coimbatore": "CBE",
      "Cuddalore": "CUD",
      "Dharmapuri": "DHP",
      "Dindigul": "DGL",
      "Erode": "ERO",
      "Kallakurichi": "KKL",
      "Kancheepuram": "KCP",
      "Kanniyakumari": "KAN",
      "Karur": "KAR",
      "Krishnagiri": "KRI",
      "Madurai": "MAD",
      "Mayiladuthurai": "MYL",
      "Nagapattinam": "NGP",
      "Namakkal": "NMK",
      "Nilgiris": "NLG",
      "Perambalur": "PER",
      "Pudukkottai": "PDK",
      "Ramanathapuram": "RMD",
      "Ranipet": "RPT",
      "Salem": "SLM",
      "Sivaganga": "SVG",
      "Tenkasi": "TKS",
      "Thanjavur": "TJV",
      "Theni": "THN",
      "Thoothukudi": "TTK",
      "Tiruchirappalli": "TRI",
      "Tirunelveli": "TNE",
      "Tirupathur": "TRP",
      "Tiruppur": "TRU",
      "Tiruvallur": "TVL",
      "Tiruvannamalai": "TVN",
      "Tiruvarur": "TVR",
      "Vellore": "VLR",
      "Villupuram": "VPM",
      "Virudhunagar": "VDR"
    }
  },
  "Tripura": {
    code: "TR",
    districts: {
      "Dhalai": "DLA",
      "Gomati": "GMT",
      "Khowai": "KHW",
      "North Tripura": "NTP",
      "Sepahijala": "SPJ",
      "South Tripura": "STP",
      "Unakoti": "UNK",
      "West Tripura": "WTP"
    }
  },

  "Uttar Pradesh": {
    code: "UP",
    districts: {
      "Agra": "AGR",
      "Aligarh": "ALG",
      "Ambedkar Nagar": "ABN",
      "Amethi": "AMT",
      "Amroha": "AMR",
      "Auraiya": "ARY",
      "Ayodhya": "AYO",
      "Azamgarh": "AZM",
      "Baghpat": "BAG",
      "Bahraich": "BHR",
      "Ballia": "BLA",
      "Balrampur": "BLR",
      "Banda": "BND",
      "Barabanki": "BRB",
      "Bareilly": "BRL",
      "Basti": "BSI",
      "Bhadohi": "BHD",
      "Bijnor": "BJN",
      "Budaun": "BDN",
      "Bulandshahr": "BLSH",
      "Chandauli": "CDA",
      "Chitrakoot": "CTK",
      "Deoria": "DOR",
      "Etah": "ETA",
      "Etawah": "ETW",
      "Farrukhabad": "FRK",
      "Fatehpur": "FTP",
      "Firozabad": "FZB",
      "Gautam Buddh Nagar": "GBN",
      "Ghaziabad": "GZB",
      "Ghazipur": "GZP",
      "Gonda": "GND",
      "Gorakhpur": "GRK",
      "Hamirpur": "HMP",
      "Hapur": "HPR",
      "Hardoi": "HRD",
      "Hathras": "HTH",
      "Jalaun": "JLN",
      "Jaunpur": "JNP",
      "Jhansi": "JHS",
      "Kannauj": "KNJ",
      "Kanpur Dehat": "KPD",
      "Kanpur Nagar": "KPN",
      "Kasganj": "KSJ",
      "Kaushambi": "KSMB",
      "Kheri": "KHE",
      "Kushinagar": "KUN",
      "Lalitpur": "LTP",
      "Lucknow": "LKO",
      "Maharajganj": "MHG",
      "Mahoba": "MHB",
      "Mainpuri": "MNP",
      "Mathura": "MTH",
      "Mau": "MUA",
      "Meerut": "MRT",
      "Mirzapur": "MRZ",
      "Moradabad": "MRD",
      "Muzaffarnagar": "MZN",
      "Pilibhit": "PLB",
      "Pratapgarh": "PTG",
      "Prayagraj": "PRY",
      "Raebareli": "RBL",
      "Rampur": "RMP",
      "Saharanpur": "SHP",
      "Sambhal": "SMB",
      "Sant Kabir Nagar": "SKN",
      "Sant Ravidas Nagar": "SRD",
      "Shahjahanpur": "SJN",
      "Shamli": "SML",
      "Shravasti": "SHV",
      "Siddharthnagar": "SDN",
      "Sitapur": "STU",
      "Sonbhadra": "SBD",
      "Sultanpur": "SLP",
      "Unnao": "UNN",
      "Varanasi": "VNS"
    }
  },
  "Uttarakhand": {
    code: "UK",
    districts: {
      "Almora": "ALM",
      "Bageshwar": "BGSW",
      "Chamoli": "CML",
      "Champawat": "CPWT",
      "Dehradun": "DDN",
      "Haridwar": "HRDW",
      "Nainital": "NNL",
      "Pauri Garhwal": "PRGW",
      "Pithoragarh": "PTHG",
      "Rudraprayag": "RDPG",
      "Tehri Garhwal": "THRG",
      "Udham Singh Nagar": "USNG",
      "Uttarkashi": "UTKS"
    }
  },

  "West Bengal": {
    code: "WB",
    districts: {
      "Alipurduar": "ALPR",
      "Bankura": "BNKRA",
      "Paschim Bardhaman": "PSBD",
      "Purba Bardhaman": "PRBD",
      "Birbhum": "BIRB",
      "Cooch Behar": "CCBH",
      "Dakshin Dinajpur": "DKDJ",
      "Darjeeling": "DJG",
      "Hooghly": "HGLY",
      "Howrah": "HWRH",
      "Jalpaiguri": "JPG",
      "Jhargram": "JHGM",
      "Kalimpong": "KLMP",
      "Kolkata": "KLK",
      "Malda": "MLDA",
      "Murshidabad": "MRSD",
      "Nadia": "NDIA",
      "North 24 Parganas": "N24P",
      "Paschim Medinipur": "PCMP",
      "Purba Medinipur": "PBMP",
      "Purulia": "PRUL",
      "South 24 Parganas": "S24P",
      "Uttar Dinajpur": "UTDJ"
    }
  },
};

export default stateDistrictMap;